-- Vespucci PD Doors

addDoorsListToConfig({

    {   
        model = 1506879043,
        coords = vector3(-1079.942, -856.074, 5.211),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_backdoor_1',
        model = -400799250,
        coords = vector3(-1051.210, -831.382, 11.326),
        locked = true,
        double = 'vpd_backdoor_2',
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_backdoor_2',
        model = -975993523,
        coords = vector3(-1049.163, -829.559, 11.326),
        locked = true,
        double = 'vpd_backdoor_1',
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },


    {   
        id = 'vpd_lobby_door_1',
        model = -400799250,
        coords = vector3(-1110.573, -824.380, 19.703),
        locked = false,
        double = 'vpd_lobby_door_2',
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_2',
        model = -975993523,
        coords = vector3(-1112.726, -826.077, 19.703),
        locked = false,
        double = 'vpd_lobby_door_1',
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_3',
        model = -400799250,
        coords = vector3(-1109.038, -841.992, 19.702),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_4',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_lobby_door_4',
        model = -975993523,
        coords = vector3(-1107.364, -844.164, 19.702),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_3',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_5',
        model = -400799250,
        coords = vector3(-1107.190, -844.391, 19.702),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_6',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_lobby_door_6',
        model = -975993523,
        coords = vector3(-1105.516, -846.562, 19.702),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_5',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_7',
        model = -400799250,
        coords = vector3(-1092.720, -810.839, 19.703),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_8',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_lobby_door_8',
        model = -975993523,
        coords = vector3(-1094.861, -812.551, 19.703),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_7',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 60, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_9',
        model = -400799250,
        coords = vector3(-1090.356, -808.948, 19.703),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_10',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_lobby_door_10',
        model = -975993523,
        coords = vector3(-1092.497, -810.661, 19.703),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_9',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_lobby_door_11',
        model = -400799250,
        coords = vector3(-1060.774, -828.794, 19.734),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_12',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_lobby_door_12',
        model = -975993523,
        coords = vector3(-1062.368, -826.564, 19.734),
        locked = false,
        autoRate = 6.0,
        double = 'vpd_lobby_door_11',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_1',
        model = -1240156945,
        coords = vector3(-1097.931, -849.737, 4.061),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_2',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_2',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 4.061),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_1',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_3',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 18.312),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_4',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_4',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 4.061),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_3',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_5',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 18.312),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_6',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    { 
        id = 'vpd_elevator_door_6',
        model = -1240156945,
        coords = vector3(-1097.931, -849.737, 18.312),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_5',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_7',
        model = -1240156945,
        coords = vector3(-1066.503, -831.986, 9.951),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_8',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_8',
        model = -1240156945,
        coords = vector3(-1067.678, -832.912, 9.951),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_7',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_9',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 25.831),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_10',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_10',
        model = -1240156945,
        coords = vector3(-1097.931, -849.737, 25.831),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_9',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_11',
        model = -1240156945,
        coords = vector3(-1066.503, -831.986, 18.312),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_12',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_12',
        model = -1240156945,
        coords = vector3(-1067.678, -832.912, 18.312),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_11',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_13',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 29.949),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_14',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_14',
        model = -1240156945,
        coords = vector3(-1097.931, -849.737, 29.949),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_13',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_elevator_door_15',
        model = -1240156945,
        coords = vector3(-1066.503, -831.986, 22.071),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_16',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_elevator_door_16',
        model = -1240156945,
        coords = vector3(-1067.678, -832.912, 22.071),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_15',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_elevator_door_17',
        model = -1240156945,
        coords = vector3(-1096.761, -848.833, 36.965),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_18',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_elevator_door_18',
        model = -1240156945,
        coords = vector3(-1097.936, -849.760, 36.965),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_17',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_elevator_door_19',
        model = -1240156945,
        coords = vector3(-1096.756, -848.811, 25.831),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_20',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_elevator_door_20',
        model = -1240156945,
        coords = vector3(-1097.931, -849.737, 25.831),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_19',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_elevator_door_20',
        model = -1240156945,
        coords = vector3(-1066.503, -831.986, 25.832),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_21',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_elevator_door_21',
        model = -1240156945,
        coords = vector3(-1067.678, -832.912, 25.832),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_elevator_door_20',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_top_parking_1',
        model = 1866464207,
        coords = vector3(-1081.526, -807.814, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_top_parking_2',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_top_parking_2',
        model = -700659261,
        coords = vector3(-1079.917, -809.856, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_top_parking_1',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },


    {   
        id = 'vpd_top_parking_3',
        model = 1866464207,
        coords = vector3(-1069.308, -826.100, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_top_parking_4',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_top_parking_4',
        model = -700659261,
        coords = vector3(-1071.349, -827.709, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_top_parking_3',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_cell_main_door',
        model = -1899592078,
        coords = vector3(-1075.152, -805.306, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {   
        id = 'vpd_mugshot_double_1',
        model = -85146317,
        coords = vector3(-1072.237, -804.793, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_mugshot_double_2',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {   
        id = 'vpd_mugshot_double_2',
        model = 1660523855,
        coords = vector3(-1073.785, -806.024, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_mugshot_double_1',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_mugshot_single',
        model = -779643538,
        coords = vector3(-1067.637, -801.764, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },


    -- Cells

    {
        id = 'vpd_holding_cell',
        model = -1899592078,
        coords = vector3(-1074.534, -801.433, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_1',
        model = -1899592078,
        coords = vector3(-1068.428, -796.619, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_2',
        model = -1899592078,
        coords = vector3(-1065.840, -794.579, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_3',
        model = -1899592078,
        coords = vector3(-1063.256, -792.541, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_4',
        model = -1899592078,
        coords = vector3(-1060.676, -790.507, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_cell_5',
        model = -1899592078,
        coords = vector3(-1058.091, -788.470, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_6',
        model = -1899592078,
        coords = vector3(-1055.507, -786.432, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_7',
        model = -1899592078,
        coords = vector3(-1052.919, -784.392, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_8',
        model = -1899592078,
        coords = vector3(-1050.027, -783.352, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_9',
        model = -1899592078,
        coords = vector3(-1048.459, -786.314, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_10',
        model = -1899592078,
        coords = vector3(-1051.043, -788.351, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_11',
        model = -1899592078,
        coords = vector3(-1056.263, -792.466, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_12',
        model = -1899592078,
        coords = vector3(-1058.847, -794.504, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_cell_13',
        model = -1899592078,
        coords = vector3(-1061.432, -796.541, 11.105),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_int_room_1',
        model = -779643538,
        coords = vector3(-1041.574, -791.084, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_int_room_2',
        model = -779643538,
        coords = vector3(-1047.433, -795.704, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_int_room_3',
        model = -779643538,
        coords = vector3(-1053.293, -800.323, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_int_room_4',
        model = -779643538,
        coords = vector3(-1059.138, -804.932, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_lineup_room',
        model = -779643538,
        coords = vector3(-1063.447, -804.082, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_reception_room',
        model = 1506879043,
        coords = vector3(-1070.884, -810.831, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_lineup_2',
        model = -779643538,
        coords = vector3(-1058.455, -811.980, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_interogation_room_1',
        model = -779643538,
        coords = vector3(-1052.361, -807.204, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_interogation_room_2',
        model = -779643538,
        coords = vector3(-1046.515, -802.595, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_interogation_room_3',
        model = -779643538,
        coords = vector3(-1040.656, -797.976, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_interogation_room_4',
        model = -779643538,
        coords = vector3(-1034.796, -793.356, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_evidence_room',
        model = -779643538,
        coords = vector3(-1044.989, -807.394, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_evidence_lockup',
        model = 1506879043,
        coords = vector3(-1048.876, -810.458, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_lockers_room',
        model = 1506879043,
        coords = vector3(-1058.206, -818.939, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_armory_room',
        model = 1506879043,
        coords = vector3(-1041.453, -822.192, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_shooting_range_room_1',
        model = -85146317,
        coords = vector3(-1037.841, -828.575, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_shooting_range_room_2',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_shooting_range_room_2',
        model = 1660523855,
        coords = vector3(-1039.072, -830.123, 11.100),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_shooting_range_room_1',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_k9_room',
        model = 1506879043,
        coords = vector3(-1072.406, -834.035, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_lower_classroom',
        model = 1506879043,
        coords = vector3(-1078.961, -839.203, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_lower_briefing_room',
        model = 1506879043,
        coords = vector3(-1084.338, -843.441, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_1',
        model = 1809703908,
        coords = vector3(-1088.988, -842.445, 11.100),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_2',
        model = 1809703908,
        coords = vector3(-1089.055, -843.943, 19.461),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_3',
        model = 1809703908,
        coords = vector3(-1089.058, -843.945, 23.236),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_4',
        model = 939003016,
        coords = vector3(-1089.625, -842.393, 26.980),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_5',
        model = 939003016,
        coords = vector3(-1090.541, -843.131, 31.099),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_stairs_6',
        model = 939003016,
        coords = vector3(-1090.541, -843.131, 34.429),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_photography_room',
        model = 876047963,
        coords = vector3(-1083.963, -835.688, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_census_room',
        model = 876047963,
        coords = vector3(-1078.717, -831.661, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_complaints_room_1',
        model = 876047963,
        coords = vector3(-1069.359, -823.276, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_complaints_room_2',
        model = 876047963,
        coords = vector3(-1068.789, -817.949, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_complaints_room_3',
        model = 876047963,
        coords = vector3(-1071.294, -813.174, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_complaints_room_4',
        model = 876047963,
        coords = vector3(-1076.052, -810.580, 19.460),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_1',
        model = -700659261,
        coords = vector3(-1071.242, -825.944, 19.461),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_2',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_2',
        model = 1866464207,
        coords = vector3(-1073.284, -827.553, 19.461),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_1',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_3',
        model = -400799250,
        coords = vector3(-1090.534, -816.991, 19.707),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_4',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_4',
        model = -975993523,
        coords = vector3(-1092.687, -818.688, 19.707),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_3',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_5',
        model = -400799250,
        coords = vector3(-1092.203, -832.511, 19.707),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_6',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_6',
        model = -975993523,
        coords = vector3(-1090.506, -834.664, 19.707),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_5',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_7',
        model = 1866464207,
        coords = vector3(-1072.704, -830.577, 23.240),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_8',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_8',
        model = -700659261,
        coords = vector3(-1071.094, -832.618, 23.240),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_7',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_9',
        model = 41520023,
        coords = vector3(-1080.520, -820.695, 23.613),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_10',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_10',
        model = 1416966037,
        coords = vector3(-1079.233, -822.333, 23.613),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_9',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_11',
        model = 1866464207,
        coords = vector3(-1095.921, -817.062, 26.980),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_12',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_12',
        model = -700659261,
        coords = vector3(-1094.312, -819.103, 26.980),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_11',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_13',
        model = 1866464207,
        coords = vector3(-1083.192, -833.208, 26.980),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_14',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_double_14',
        model = -700659261,
        coords = vector3(-1081.582, -835.250, 26.980),
        locked = true,
        autoRate = 6.0,
        double = 'vpd_random_double_13',
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_1',
        model = 876047963,
        coords = vector3(-1068.310, -814.445, 23.629),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_2',
        model = -709325610,
        coords = vector3(-1079.935, -821.122, 27.151),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_3',
        model = 1022516300,
        coords = vector3(-1083.920, -810.236, 26.984),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_4',
        model = -709325610,
        coords = vector3(-1078.563, -817.093, 27.151),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_5',
        model = -709325610,
        coords = vector3(-1076.219, -825.835, 27.151),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_6',
        model = 2078407975,
        coords = vector3(-1070.559, -832.997, 26.880),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_7',
        model = 1866464207,
        coords = vector3(-1101.064, -827.939, 31.098),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_8',
        model = 1809703908,
        coords = vector3(-1104.111, -830.996, 34.429),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_random_single_9',
        model = 1506879043,
        coords = vector3(-1107.739, -832.060, 38.094),
        locked = true,
        autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },


    -- VPD Vehicle Related Doors

    { 
        id = 'vpd_bottom_left',
        model = 239547910,
        coords = vector3(-1075.040, -852.372, 5.734),
        locked = true,
        special = true,
        --autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    { 
        id = 'vpd_bottom_right',
        model = 239547910,
        coords = vector3(-1071.060, -849.235, 5.736),
        locked = true,
        special = true,
        --autoRate = 6.0,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },

    {
        id = 'vpd_upper_garage',
        model = -1212944997,
        coords = vector3(-1120.992, -834.935, 16.270),
        locked = true,
        special = true,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_bollards_enter',
        model = 110624687,
        coords = vector3(-1147.369, -847.197, 13.445),
        autoRate = 1.0,
        autoDist = 7.0,
        locked = true,
        special = true,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = false },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
    {
        id = 'vpd_back_fence',
        model = 1185512375,
        coords = vector3(-1066.359, -881.159, 3.925),
        locked = true,
        special = true,
        restricted = {
            { type = 'job', job = 'police', workplace = false, gradeLevel = 0, jobPermission = false, reqDuty = true },
            { type = 'job', job = 'government', workplace = 'doj', gradeLevel = 10, jobPermission = false, reqDuty = true },
        },
    },
})